apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://CAMBIAR_HOST_MYSQL:3306/CAMBIAR_NOMBRE_BD"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "admin123"
