apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 348374603543.dkr.ecr.us-east-1.amazonaws.com/prueba_devops_2-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: VENTAS_BACK_HOST
          value: ventas-service:80
        - name: DESPACHOS_BACK_HOST
          value: despachos-service:80
